try:
    print('hello'+99)
except Exception as e:
    print('exception thrown!')

print('letus continue the program though it has got error')